import{Page}from'../components/Layout';import{PageHeader,State,Card,PrintButton,fmt}from'../components/UI';import{useResearch}from'../lib/useResearch';import{RiskMap}from'../features/map/RiskMap';import{BurdenChart,ImportanceChart,ObservedPredicted}from'../features/charts/Charts';import{Benchmark}from'../features/models/Benchmark';import{SpatialPanel}from'../features/spatial/SpatialPanel';import{Readiness}from'../features/readiness/Readiness';
function DataPage({children}:{children:(data:NonNullable<ReturnType<typeof useResearch>['data']>)=>React.ReactNode}){const r=useResearch();return <Page>{r.data?children(r.data):<State loading={r.loading} error={r.error}/>}</Page>}
export const RiskMapPage=()=> <Page><PageHeader eyebrow="GIS / Papua" title="Papua GIS Risk Map" lead="Layer-controlled retrospective research map. Boundary and facility layers remain disconnected until licensed datasets are supplied."/><RiskMap/></Page>;
export const Surveillance=()=> <DataPage>{d=><><PageHeader eyebrow="Epidemiological surveillance" title="Malaria Surveillance" lead="Verified aggregate burden with missing years left explicitly unavailable."/><div className="two"><BurdenChart data={d.burden.annual}/><Card><h2>Panel construction</h2><dl><dt>Balanced forecasting panel</dt><dd>8 districts · 48 district-years</dd><dt>2025 spatial assessment</dt><dd>9 districts</dd><dt>Supiori</dt><dd>Excluded from forecasting because the 2024 outcome was unavailable.</dd></dl></Card></div></>}</DataPage>;
export const Climate=()=> <Page><PageHeader eyebrow="Climate intelligence" title="Climate–Malaria Intelligence" lead="NASA POWER is an intended public climate source; no climate observations were supplied in the verified brief."/><div className="empty-panel"><CloudPlaceholder/><h2>Dataset not connected</h2><p>Climate time series and climate–malaria comparison plots will appear only after an authorized dataset is added with provenance.</p></div></Page>;
function CloudPlaceholder(){return <span className="empty-icon">☁</span>}
export const Forecasting=()=> <DataPage>{d=><><PageHeader eyebrow="Temporal forecasting" title="Forecasting" lead="Leakage-resistant temporal validation with an untouched 2025 test."/><Benchmark data={d}/></>}</DataPage>;
export const Spatial=()=> <DataPage>{d=><><PageHeader eyebrow="Spatial epidemiology" title="Spatial Analysis" lead="Global autocorrelation and descriptive heterogeneity, interpreted without overstating statistical evidence."/><SpatialPanel data={d}/><RiskMap/></>}</DataPage>;
export const Models=()=> <DataPage>{d=><><PageHeader eyebrow="Honest model evaluation" title="Model Benchmarking" lead="Climate-informed machine learning did not outperform persistence on the primary 2025 MAE." actions={<PrintButton/>}/><Benchmark data={d}/></>}</DataPage>;
export const Intelligence=()=> <DataPage>{d=><><PageHeader eyebrow="Retrospective intelligence" title="MALARIASCOPE Research Intelligence" lead="Risk context, prediction limitations, and readiness prompts—not operational directives."/><div className="kpis"><Card><small>Current research risk</small><strong>VERY HIGH</strong><span>Mamberamo Raya result only</span></Card><Card><small>Highest incidence</small><strong>{d.spatial.highestIncidence.per1000}</strong><span>per 1,000 · 2025</span></Card><Card><small>Model confidence</small><strong>LIMITED</strong><span>RF underperformed persistence on MAE</span></Card><Card><small>Spatial signal</small><strong>I = {d.spatial.moransI}</strong><span>p = {d.spatial.permutationP}</span></Card></div><div className="two"><BurdenChart data={d.burden.annual}/><ImportanceChart predictor={d.models.leadingPredictor}/></div><ObservedPredicted/><Readiness/></>}</DataPage>;
export const ForceHealth=()=> <Page><PageHeader eyebrow="Force health protection" title="Readiness Decision Support" lead="Prompts for multidisciplinary review using authorized local evidence and command processes."/><Readiness/><Card className="guardrail"><h2>Operational-security guardrails</h2><ul><li>No troop positions, routes, identities, schedules, or classified information.</li><li>Future mobility inputs must be de-identified, aggregated, authorized, and access-controlled.</li><li>Outputs never replace clinical judgment, public-health authority, or operational command.</li></ul></Card></Page>;
