import React from 'react';import {Link} from 'react-router-dom';import {ArrowRight,Play,ShieldCheck} from 'lucide-react';import {articles,products,toolCards,availableCounts,statusLabel} from '../data/content';import {Button,Card,Badge,Icon} from '../components/ui/UI';import {HeroScene} from '../components/three/HeroScene';
const SectionTitle=({kicker,title,desc,link})=><div className="section-title"><div><span>{kicker}</span><h2>{title}</h2>{desc&&<p>{desc}</p>}</div>{link&&<Link to={link}>Lihat semua <ArrowRight size={16}/></Link>}</div>;
export function Home(){return <>
 <section className="hero"><div className="hero-grid wrap"><div className="hero-copy"><Badge tone="soft"><span className="dot"/> Medical Education · Research · Innovation</Badge><h1>Ilmu Kedokteran.<br/><em>Teknologi.</em> Dampak Nyata.</h1><p>Platform edukasi kesehatan digital yang menghubungkan pengetahuan klinis, riset, dan inovasi untuk pelayanan kesehatan yang lebih baik.</p><div className="hero-actions"><Button to="/belajar/ekg">Mulai Belajar <ArrowRight size={18}/></Button><Button to="/simulator" variant="outline"><Play size={17}/> Buka Simulator</Button></div><div className="trust"><span><b>Konten edukasi dengan status yang transparan</b><small>Tersedia, demo, atau segera hadir</small></span></div></div><HeroScene/></div><div className="stats wrap"><div><b>{availableCounts.articles}</b><span>Artikel Tersedia</span></div><div><b>{availableCounts.tools}</b><span>Tools Tersedia</span></div><div><b>{availableCounts.learningLabs}</b><span>Learning Lab Tersedia</span></div><div><b>{availableCounts.simulators}</b><span>Simulator Tersedia</span></div></div></section>
 <section className="wrap action-paths" aria-labelledby="action-title"><div className="action-intro"><span className="eyebrow">Mulai dari sini</span><h2 id="action-title">Pilih langkah berikutnya</h2><p>Tiga jalur utama untuk melanjutkan kegiatan Anda.</p></div><div className="action-grid"><Link to="/belajar"><span>01</span><div><b>Lanjutkan belajar</b><small>Buka lab dan progres tersimpan</small></div><ArrowRight/></Link><Link to="/simulator"><span>02</span><div><b>Mulai latihan</b><small>Asah keputusan melalui simulasi</small></div><ArrowRight/></Link><Link to="/research-lab"><span>03</span><div><b>Buka workspace riset</b><small>Susun PICO dan strategi pencarian</small></div><ArrowRight/></Link></div></section>
 <section className="section wrap"><SectionTitle kicker="Wawasan Klinis" title="Artikel terbaru" desc="Pengetahuan kesehatan yang relevan, ringkas, dan berbasis bukti." link="/artikel"/><div className="articles-grid">{articles.slice(0,3).map((a,i)=><Card className="article-card" key={a.slug}><div className={`article-art art-${i}`}><Icon name={a.icon} size={42}/><Badge>{a.category}</Badge></div><div className="card-body"><div className="meta"><span>{a.evidence}</span><span>•</span><span>{a.read}</span></div><h3>{a.title}</h3><p>{a.excerpt}</p><Link to={`/artikel/${a.slug}`}>Baca artikel <ArrowRight size={15}/></Link></div></Card>)}</div></section>
 <section className="section pale"><div className="wrap"><SectionTitle kicker="Belajar dengan Praktik" title="Tools & learning lab" desc="Ruang belajar interaktif untuk mengasah pemahaman dan pengambilan keputusan." link="/tools"/><div className="tool-grid">{toolCards.map((x,i)=><Link to={x.route} className="tool-card" key={x.id}><div className={`tool-icon t${i}`}><Icon name={x.icon}/></div><div><Badge>{statusLabel[x.status]}</Badge><h3>{x.title}</h3><p>{x.desc}</p><span>Eksplorasi modul <ArrowRight size={15}/></span></div></Link>)}</div></div></section>
 <section className="section wrap"><SectionTitle kicker="Simulasi Klinis" title="Belajar mengambil keputusan" desc="Skenario aman dan terstruktur untuk melatih alur pikir klinis." link="/simulator"/><div className="sim-feature"><div className="sim-monitor"><div className="monitor-top"><span>ACLS TRAINING MONITOR</span><i>● LIVE</i></div><svg viewBox="0 0 600 120"><polyline points="0,65 80,65 95,20 112,100 130,52 145,65 250,65 268,20 285,100 302,52 318,65 430,65 448,20 465,100 482,52 500,65 600,65"/></svg><div className="vitals"><b>72<small>HR</small></b><b>98<small>SpO₂</small></b><b>36<small>ETCO₂</small></b></div></div><div className="sim-copy"><Badge>SIMULATOR UNGGULAN</Badge><h2>ACLS Interaktif & MegaCode</h2><p>Latih respons sistematis dalam skenario kegawatdaruratan—mulai dari identifikasi ritme hingga debrief edukatif.</p><ul><li>Monitor dan tanda vital dinamis</li><li>Log tindakan & code clock</li><li>Skor dan debrief personal</li></ul><Button to="/simulator/acls">Mulai simulasi <ArrowRight size={17}/></Button></div></div></section>
 <section className="section pale"><div className="wrap"><SectionTitle kicker="Karya Digital" title="Dibuat untuk belajar lebih efektif" link="/produk"/><div className="product-row">{products.slice(0,3).map((p,i)=><Card key={p.title} className="mini-product"><div className={`cover ${p.tone}`}><small>drsobri.id</small><Icon name={i===0?'Microscope':i===1?'Presentation':'FileCheck'} size={40}/><b>{p.title}</b></div><div><Badge>{p.category}</Badge><h3>{p.title}</h3><p>{p.desc}</p><b>{p.price}</b></div></Card>)}</div></div></section>
 <section className="profile-band"><div className="wrap profile-grid"><div className="portrait"><div className="portrait-placeholder">SM</div><div className="quote">“Teknologi terbaik adalah yang memperkuat kemanusiaan dalam pelayanan kesehatan.”</div></div><div><div className="eyebrow">Tentang Founder</div><h2>Kapten Kes dr. Muhammad<br/>Sobri Maulana</h2><p className="credentials">S.Kom, CEH, OSCP, OSCE</p><p>Dokter, praktisi keamanan siber, dan pendidik yang berfokus pada titik temu antara kedokteran, teknologi, serta keselamatan pasien.</p><div className="expertise"><span>Military Medicine</span><span>Digital Health</span><span>Cybersecurity</span><span>Medical Education</span></div><Button to="/profil" variant="light">Kenali lebih lanjut <ArrowRight size={17}/></Button></div></div></section>
 <section className="disclaimer wrap"><ShieldCheck/><div><b>Catatan penting</b><p>Seluruh konten di drsobri.id ditujukan untuk edukasi dan tidak menggantikan konsultasi, diagnosis, atau penanganan oleh tenaga kesehatan profesional.</p></div><Link to="/legal/disclaimer">Baca disclaimer lengkap</Link></section>
 </>}
