import React,{useEffect,useState} from 'react';
import {Check,Eye,EyeOff,Search,Target} from 'lucide-react';
import {Badge,Button,PageHead,Progress} from '../components/ui/UI';
import {learningModules} from '../data/learningModules';
import {readStorage,writeStorage} from '../utils/storage';

const tabs=['Materi','Latihan','Kasus','Evaluasi'];
const emptyProgress={};
const labels={new:'Belum mulai',studying:'Sedang dipelajari',studied:'Selesai dipelajari',passed:'Lulus latihan'};
const normalize=x=>x&&typeof x==='object'&&!Array.isArray(x)?x:emptyProgress;

export function LearningLab({kind}){
 const module=learningModules[kind];
 const [tab,setTab]=useState('Materi'),[caseId,setCaseId]=useState(module.cases[0].id),[progress,setProgress]=useState(()=>readStorage(`learning-progress-${kind}`,{},normalize));
 const [response,setResponse]=useState(''),[feedback,setFeedback]=useState(null),[step,setStep]=useState(0),[labelsVisible,setLabelsVisible]=useState(true),[zoom,setZoom]=useState(false),[hotspots,setHotspots]=useState([]);
 const item=module.cases.find(x=>x.id===caseId),status=progress[caseId]||'new';
 useEffect(()=>{setTab('Materi');setCaseId(module.cases[0].id);setProgress(readStorage(`learning-progress-${kind}`,{},normalize));setResponse('');setFeedback(null);setStep(0)},[kind,module]);
 useEffect(()=>{setResponse('');setFeedback(null);setStep(0);setHotspots([])},[caseId]);
 const completed=Object.values(progress).filter(x=>x==='studied'||x==='passed').length;
 function save(next){setProgress(next);writeStorage(`learning-progress-${kind}`,next)}
 function begin(id){setCaseId(id);if(!progress[id])save({...progress,[id]:'studying'})}
 function studied(){save({...progress,[caseId]:'studied'})}
 function evaluate(){const expected=kind==='ekg'?Object.values(item.answers).join(' '):item.answer;const words=expected.toLowerCase().split(/\W+/).filter(x=>x.length>3);const ok=words.some(x=>response.toLowerCase().includes(x));setFeedback(ok?{ok:true,text:`Tepat. ${item.explanation}`}:{ok:false,text:`Belum tepat. Bandingkan jawaban Anda dengan temuan kunci: ${kind==='ekg'?item.answers.interpretation:item.answer}. ${item.explanation}`});if(ok)save({...progress,[caseId]:'passed'})}
 return <><PageHead eyebrow="Learning Lab" title={module.title} desc={module.desc}/><main className="wrap learning lab-shell"><section className="learning-top"><div><span>Progres modul</span><b>{completed}/{module.cases.length} kasus dipelajari · {Object.values(progress).filter(x=>x==='passed').length} lulus</b></div><Progress value={completed/module.cases.length*100}/></section><div className="lab-objectives"><Target/><div><b>Tujuan belajar</b><span>{module.objectives.join(' · ')}</span></div></div><div className="tabs lab-tabs" role="tablist">{tabs.map(x=><button key={x} role="tab" aria-selected={tab===x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="lab-workspace"><aside className="case-rail"><b>Pilih kasus</b>{module.cases.map((x,i)=><button key={x.id} className={caseId===x.id?'active':''} onClick={()=>begin(x.id)}><span>{String(i+1).padStart(2,'0')}</span><div>{x.title}<small>{labels[progress[x.id]||'new']}</small></div></button>)}</aside><section className="lab-main"><header className="case-heading"><div><Badge>{labels[status]}</Badge><h2>{item.title}</h2><p>{item.summary}</p></div><small>Kriteria: {module.completion}</small></header>{tab==='Materi'&&<Material module={module} item={item} kind={kind} onStudied={studied} labelsVisible={labelsVisible} setLabelsVisible={setLabelsVisible} zoom={zoom} setZoom={setZoom} hotspots={hotspots} setHotspots={setHotspots}/>} {tab==='Latihan'&&<Practice kind={kind} item={item} response={response} setResponse={setResponse} feedback={feedback} evaluate={evaluate} step={step} setStep={setStep}/>} {tab==='Kasus'&&<CaseView kind={kind} module={module} item={item}/>} {tab==='Evaluasi'&&<Evaluation kind={kind} item={item} response={response} setResponse={setResponse} feedback={feedback} evaluate={evaluate}/>}</section></div><References items={module.references}/><p className="medical-note">Untuk edukasi, bukan diagnosis atau alat keputusan klinis. Interpretasikan bersama konteks dan pedoman yang berlaku.</p></main></>
}

function Material({module,item,kind,onStudied,labelsVisible,setLabelsVisible,zoom,setZoom,hotspots,setHotspots}){return <div className="lab-panel"><h3>Materi inti</h3><ul>{item.material.map(x=><li key={x}>{x}</li>)}</ul><Visual kind={kind} module={module} item={item} labelsVisible={labelsVisible} zoom={zoom} hotspots={hotspots} setHotspots={setHotspots}/><div className="visual-tools">{kind==='cxr'&&<button onClick={()=>setZoom(!zoom)}><Search/> {zoom?'Ukuran normal':'Zoom 1,5×'}</button>}{kind==='osteology'&&<button onClick={()=>setLabelsVisible(!labelsVisible)}>{labelsVisible?<EyeOff/>:<Eye/>} {labelsVisible?'Sembunyikan label':'Tampilkan label'}</button>}</div><Button onClick={onStudied}><Check/> Tandai selesai dipelajari</Button><p className="action-note">Membuka kasus hanya mengubah status menjadi “sedang dipelajari”. Gunakan tombol ini setelah menuntaskan materi.</p></div>}
function Practice({kind,item,response,setResponse,feedback,evaluate,step,setStep}){if(kind==='cxr'){const parts=['A — Airway','B — Breathing','C — Circulation','D — Diaphragm','E — Everything else'];return <div className="lab-panel"><h3>Checklist ABCDE bertahap</h3><div className="stepper">{parts.map((x,i)=><button key={x} className={i<=step?'done':''} onClick={()=>setStep(i)}>{i<step?<Check/>:i+1} {x}</button>)}</div><p>Catat temuan untuk <b>{parts[step]}</b>. Setelah semua tahap, tuliskan kesimpulan.</p>{step<4?<Button onClick={()=>setStep(step+1)}>Simpan & lanjutkan</Button>:<AnswerBox {...{response,setResponse,feedback,evaluate}}/>}</div>}
 if(kind==='ekg')return <div className="lab-panel"><h3>Interpretasi lima komponen</h3><div className="structured-grid">{['Rate','Rhythm','Axis','Interval','Interpretasi'].map(x=><label key={x}>{x}<input aria-label={x} placeholder={`Masukkan ${x.toLowerCase()}`}/></label>)}</div><AnswerBox {...{response,setResponse,feedback,evaluate}} placeholder="Tulis kesimpulan akhir..."/></div>;
 return <div className="lab-panel"><h3>Kuis identifikasi</h3><p>Amati orientasi dan landmark. Tuliskan nama tulang beserta sisinya.</p><AnswerBox {...{response,setResponse,feedback,evaluate}}/></div>}
function CaseView({kind,module,item}){return <div className="lab-panel"><h3>Kasus dan visual</h3><p>{item.summary}</p><Visual kind={kind} module={module} item={item} labelsVisible={false} hotspots={[]} setHotspots={()=>{}}/><div className="finding"><b>Temuan yang harus dikenali</b><p>{kind==='ekg'?`Rate ${item.answers.rate}; ${item.answers.rhythm}; ${item.answers.interval}.`:kind==='cxr'?item.finding:item.material.join(' ')}</p></div></div>}
function Evaluation(props){return <div className="lab-panel"><h3>Evaluasi akhir</h3><p>Jawab tanpa membuka materi. Jawaban benar mengubah status menjadi <b>lulus latihan</b>.</p><AnswerBox {...props}/></div>}
function AnswerBox({response,setResponse,feedback,evaluate,placeholder='Tulis diagnosis atau identifikasi...'}){return <><textarea className="answer-input" value={response} onChange={e=>setResponse(e.target.value)} placeholder={placeholder}/><Button disabled={!response.trim()} onClick={evaluate}>Periksa jawaban</Button>{feedback&&<div className={`specific-feedback ${feedback.ok?'correct':'retry'}`} role="status"><b>{feedback.ok?'Benar':'Coba lagi'}</b><p>{feedback.text}</p></div>}</>}
function Visual({kind,module,item,labelsVisible=true,zoom=false,hotspots=[],setHotspots}){if(kind==='ekg')return <div className="ecg-paper lab-visual"><svg viewBox="0 0 900 180" preserveAspectRatio="none"><polyline points={wave[item.pattern]}/></svg><b>Waveform sintetis untuk edukasi — bukan rekaman klinis nyata</b><span>Kecepatan 25 mm/s · amplitudo 10 mm/mV · Lead II simulasi</span></div>;if(kind==='cxr')return <div className={`cxr-illustration ${zoom?'zoomed':''}`}><div className="cxr-body"><i className="cxr-lung l"/><i className="cxr-lung r"/><i className="cxr-spine"/>{item.marker!=='none'&&<em className={item.marker}>Temuan</em>}</div><span>ILUSTRASI SKEMATIK BERLABEL · bukan radiograf pasien · tidak untuk diagnosis</span></div>;return <div className="bone-illustration"><div className={`bone-shape ${item.id}`}/>{item.landmarks.map(([name,x,y],i)=><button key={name} style={{left:`${x}%`,top:`${y}%`}} className={hotspots.includes(i)?'open':''} onClick={()=>setHotspots([...new Set([...hotspots,i])])}><i>{i+1}</i>{labelsVisible||hotspots.includes(i)?<span>{name}</span>:null}</button>)}<small>Ilustrasi skematik · klik hotspot untuk membuka landmark</small></div>}
const wave={sinus:'0,100 75,100 82,88 90,100 115,100 122,45 130,145 140,80 152,100 190,100 205,85 225,100 300,100 307,88 315,100 340,100 347,45 355,145 365,80 377,100 415,100 430,85 450,100 525,100 532,88 540,100 565,100 572,45 580,145 590,80 602,100 640,100 655,85 675,100 900,100',af:'0,105 20,98 45,108 70,95 92,104 110,45 120,145 132,82 150,105 178,95 205,108 235,92 265,104 275,45 285,145 298,82 320,106 350,92 390,108 430,96 460,104 470,45 480,145 493,82 515,105 550,95 590,108 625,92 660,104 670,45 680,145 693,82 715,106 750,92 790,108 830,96 900,104',av1:'0,100 40,90 55,100 105,100 112,45 120,145 132,80 145,100 220,100 260,90 275,100 325,100 332,45 340,145 352,80 365,100 440,100 480,90 495,100 545,100 552,45 560,145 572,80 585,100 660,100 700,90 715,100 765,100 772,45 780,145 792,80 805,100 900,100'};
function References({items}){return <section className="lab-references"><h3>Referensi modul</h3>{items.map(x=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.label}</a>)}</section>}
