import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {AlertTriangle,ArrowRight,BookOpen,CheckCircle2,Clock,Download,FileUp,Flag,RefreshCw,RotateCcw,Trash2} from 'lucide-react';
import {Badge,Button,Card,PageHead,Progress} from '../components/ui/UI';
import {btkvBlueprint,questions} from '../data/questionBank';
import {initialBankProgress,officialScore,recommendation,shuffledIds,topicStats} from '../utils/questionEngine';
import {readStorage,writeStorage} from '../utils/storage';

const key='dr-question-bank';
const valid=v=>v&&Array.isArray(v.answers)&&v.notes&&Array.isArray(v.unsure);
const modes=[['belajar','Mode belajar','Umpan balik langsung'],['topik','Latihan topik','Fokus area tertentu'],['ujian','Ujian berwaktu','Hanya soal terverifikasi'],['salah','Ulangi jawaban salah','Perkuat titik lemah']];
export function QuestionBank(){
 const [data,setData]=useState(()=>readStorage(key,initialBankProgress(),valid));const [view,setView]=useState('dashboard');const [mode,setMode]=useState('belajar');const [topic,setTopic]=useState('semua');
 const [queue,setQueue]=useState([]),[index,setIndex]=useState(0),[choice,setChoice]=useState(null),[revealed,setRevealed]=useState(false),[seconds,setSeconds]=useState(0);const file=useRef();
 useEffect(()=>writeStorage(key,data),[data]);useEffect(()=>{if(view!=='session'||mode!=='ujian')return;if(seconds<=0){setView('dashboard');return}const t=setInterval(()=>setSeconds(x=>x-1),1000);return()=>clearInterval(t)},[view,mode,seconds]);
 const stats=topicStats(questions,data.answers),rec=recommendation(questions,data.answers),score=officialScore(data.answers);const answered=new Set(data.answers.map(x=>x.questionId));
 function poolFor(nextMode=mode){let pool=questions.filter(q=>topic==='semua'||q.topik===topic);if(nextMode==='ujian')pool=pool.filter(q=>q.statusReview==='terverifikasi');if(nextMode==='salah'){const wrong=new Set(data.answers.filter(x=>!x.correct).map(x=>x.questionId));pool=pool.filter(q=>wrong.has(q.id))}return pool}
 function start(nextMode=mode,forcedTopic=null){let pool=poolFor(nextMode);if(forcedTopic)pool=questions.filter(q=>q.topik===forcedTopic);if(!pool.length)return alert('Belum ada soal yang sesuai filter ini.');setMode(nextMode);setQueue(shuffledIds(pool,data.queue));setIndex(0);setChoice(null);setRevealed(false);setSeconds(nextMode==='ujian'?20*60:0);setView('session')}
 const current=questions.find(q=>q.id===queue[index]);
 function answer(){if(choice===null)return;const official=mode==='ujian'&&current.statusReview==='terverifikasi',row={id:`${Date.now()}-${current.id}`,questionId:current.id,topic:current.topik,choice,correct:choice===current.jawabanTerbaik,official,mode,at:new Date().toISOString()};setData(d=>({...d,answers:[...d.answers,row],queue:[...new Set([...d.queue,current.id])]}));setRevealed(true)}
 function next(){if(index+1>=queue.length){setView('dashboard');return}setIndex(x=>x+1);setChoice(null);setRevealed(false)}
 function toggle(field,id){setData(d=>({...d,[field]:d[field].includes(id)?d[field].filter(x=>x!==id):[...d[field],id]}))}
 function addCard(){setData(d=>({...d,flashcards:{...d.flashcards,[current.id]:!d.flashcards[current.id]},schedule:{...d.schedule,[current.id]:new Date(Date.now()+86400000).toISOString()}}))}
 function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='drsobri-progres-btkv.json';a.click();URL.revokeObjectURL(url)}
 function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!valid(parsed))throw Error();setData(parsed)}catch{alert('Berkas progres tidak valid.')}};r.readAsText(f);e.target.value=''}
 function erase(){if(confirm('Hapus seluruh progres bank soal di perangkat ini?'))setData(initialBankProgress())}
 if(view==='session'&&current)return <Session q={current} mode={mode} index={index} total={queue.length} choice={choice} setChoice={setChoice} revealed={revealed} answer={answer} next={next} seconds={seconds} note={data.notes[current.id]||''} setNote={value=>setData(d=>({...d,notes:{...d.notes,[current.id]:value}}))} unsure={data.unsure.includes(current.id)} toggleUnsure={()=>toggle('unsure',current.id)} flashcard={Boolean(data.flashcards[current.id])} addCard={addCard} quit={()=>setView('dashboard')}/>;
 return <><PageHead eyebrow="Bank Soal · Jalur Unggulan" title="Dashboard Pembelajaran BTKV" desc="Latihan bedah toraks, kardiak, dan vaskular yang terukur—untuk belajar, bukan klaim sertifikasi."/><main className="wrap bank-page"><div className="bank-notice"><AlertTriangle/><span><b>Ruang latihan mandiri.</b> Soal draft terlihat di mode belajar, tetapi tidak pernah masuk evaluasi atau skor resmi.</span></div><section className="bank-kpis"><Card><b>{data.answers.length}</b><span>Jawaban terekam</span></Card><Card><b>{score.total?Math.round(score.correct/score.total*100):0}%</b><span>Akurasi evaluasi resmi</span></Card><Card><b>{answered.size}/30</b><span>Progres bank soal</span><Progress value={answered.size/30*100}/></Card><Card><b>{data.unsure.length}</b><span>Ditandai ragu</span></Card></section><section className="bank-layout"><div><Card className="start-panel"><Badge>30 SOAL · 8 DOMAIN</Badge><h2>Mulai sesi baru</h2><label>Filter topik<select value={topic} onChange={e=>setTopic(e.target.value)}><option value="semua">Semua topik BTKV</option>{btkvBlueprint.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><div className="mode-grid">{modes.map(([id,label,desc])=><button key={id} onClick={()=>start(id)}><span>{id==='ujian'?<Clock/>:<BookOpen/>}</span><b>{label}</b><small>{desc}</small><ArrowRight/></button>)}</div></Card><h2>Blueprint BTKV</h2><div className="blueprint-grid">{btkvBlueprint.map(x=>{const s=stats[x.id]||{correct:0,total:0};return <Card key={x.id}><div><b>{x.label}</b><span>{questions.filter(q=>q.topik===x.id).length} soal</span></div><strong>{s.total?Math.round(s.correct/s.total*100):'—'}%</strong><Progress value={s.total?s.correct/s.total*100:0}/><small>{s.total} jawaban · target blueprint {x.target}</small></Card>})}</div></div><aside><Card className="recommend-card"><Badge>REKOMENDASI TRANSPARAN</Badge><h3>Fokus: {btkvBlueprint.find(x=>x.id===rec.topic)?.label}</h3><p>{rec.reason}</p><button onClick={()=>{setTopic(rec.topic);start('topik',rec.topic)}}>Latih area ini <ArrowRight/></button><small>Aturan: pilih topik dengan akurasi terendah dari seluruh jawaban tersimpan. Jika belum ada hasil, mulai dari anatomi.</small></Card><Card className="study-tools"><h3>Alat belajar</h3><p><b>{Object.values(data.flashcards).filter(Boolean).length} flashcard</b><span>Jadwal berikutnya otomatis +1 hari saat kartu dibuat.</span></p><p><b>{Object.keys(data.notes).filter(k=>data.notes[k]).length} catatan pribadi</b><span>Catatan hanya tersimpan di perangkat ini.</span></p><h3>Kelola data lokal</h3><div className="data-actions"><button onClick={exportData}><Download/> Ekspor</button><button onClick={()=>file.current.click()}><FileUp/> Impor</button><button className="danger" onClick={erase}><Trash2/> Hapus</button><input ref={file} hidden type="file" accept="application/json" onChange={importData}/></div></Card></aside></section></main></>;
}

function Session({q,mode,index,total,choice,setChoice,revealed,answer,next,seconds,note,setNote,unsure,toggleUnsure,flashcard,addCard,quit}){const mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0');return <main className="wrap quiz-page"><header className="quiz-head"><button onClick={quit}>← Dashboard</button><div><span>Soal {index+1} dari {total}</span><Progress value={(index+1)/total*100}/></div>{mode==='ujian'?<b><Clock/> {mm}:{ss}</b>:<Badge>{mode.toUpperCase()}</Badge>}</header><div className="quiz-layout"><Card className="question-card"><div className="question-meta"><Badge>{q.bidang} · {q.subtopik}</Badge><span className={`review-pill ${q.statusReview}`}>{q.statusReview==='draft'?'DRAFT · tidak dinilai':'TERVERIFIKASI'}</span><span>{q.tingkatKesulitan}</span></div><p className="objective">Tujuan: {q.tujuanBelajar}</p><h1>{q.vignette}</h1><div className="options">{q.opsi.map((o,i)=><button disabled={revealed} className={`${choice===i?'selected':''} ${revealed&&i===q.jawabanTerbaik?'correct':''} ${revealed&&choice===i&&i!==q.jawabanTerbaik?'wrong':''}`} onClick={()=>setChoice(i)} key={o}><i>{String.fromCharCode(65+i)}</i><span>{o}</span></button>)}</div>{!revealed?<Button disabled={choice===null} onClick={answer}>Kunci jawaban</Button>:<div className="explanation" aria-live="polite"><h3>{choice===q.jawabanTerbaik?<><CheckCircle2/> Tepat</>:<><AlertTriangle/> Perlu ditinjau</>}</h3>{q.pembahasanOpsi.map((x,i)=><p key={x}><b>{String.fromCharCode(65+i)}.</b> {x}</p>)}{choice!==q.jawabanTerbaik&&<Link to={q.learningLink}>Pelajari di learning lab terkait <ArrowRight/></Link>}<h4>Referensi</h4>{q.referensi.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer">{r.label}</a>)}<Button onClick={next}>Soal berikutnya <ArrowRight/></Button></div>}</Card><aside><Card><button className={`tool-toggle ${unsure?'active':''}`} onClick={toggleUnsure}><Flag/> {unsure?'Ditandai ragu':'Tandai ragu'}</button><button className={`tool-toggle ${flashcard?'active':''}`} onClick={addCard}><RotateCcw/> {flashcard?'Flashcard tersimpan':'Jadikan flashcard'}</button><label className="note-field">Catatan pribadi<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Tulis pengingat atau reasoning…"/></label></Card><p className="medical-note">Pilihan soal berikutnya mengganti pertanyaan dan mereset opsi. Antrean diacak tanpa pengulangan sampai kumpulan habis.</p></aside></div></main>}
