import React,{useEffect,useMemo,useState} from 'react';
import {Copy,Download,FileUp,Plus,Trash2} from 'lucide-react';
import {Badge,Button,Card,PageHead} from '../components/ui/UI';
import {buildQuery,DATABASES,deduplicate,parseImport,prisma} from '../utils/research';
import {readStorage,writeStorage} from '../utils/storage';

const starter=[{id:'p',label:'Population / Problem',terms:[''],included:true},{id:'i',label:'Intervention',terms:[''],included:true},{id:'c',label:'Comparison',terms:[''],included:false},{id:'o',label:'Outcome',terms:[''],included:false}];
const valid=x=>x&&Array.isArray(x.concepts)&&Array.isArray(x.searches)&&Array.isArray(x.records);
const fresh={framework:'PICO',concepts:starter,yearFrom:'',yearTo:'',studyType:'all',database:'PubMed',platform:'PubMed',searches:[],records:[],extraction:[]};
const saveFile=(name,data,type='application/json')=>{const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
export function Research(){
 const [workspace,setWorkspace]=useState(()=>readStorage('research-workspace',fresh,valid));const [tab,setTab]=useState('strategy');
 const w=workspace,set=patch=>setWorkspace(old=>({...old,...patch}));
 useEffect(()=>writeStorage('research-workspace',workspace),[workspace]);
 const output=useMemo(()=>buildQuery(w),[w]),flow=useMemo(()=>prisma(w.records),[w.records]);
 function framework(value){set({framework:value,concepts:w.concepts.map((c,i)=>({...c,label:i===1?(value==='PICO'?'Intervention':'Exposure'):c.label}))})}
 function concept(id,patch){set({concepts:w.concepts.map(c=>c.id===id?{...c,...patch}:c)})}
 function addTerm(id){const c=w.concepts.find(x=>x.id===id);concept(id,{terms:[...c.terms,'']})}
 function logSearch(){if(!output.query)return;set({searches:[...w.searches,{id:crypto.randomUUID(),database:w.database,platform:w.platform,date:new Date().toISOString().slice(0,10),query:output.query,count:'',file:''}]})}
 function updateSearch(id,patch){set({searches:w.searches.map(x=>x.id===id?{...x,...patch}:x)})}
 function importRecords(e){const file=e.target.files[0];if(!file)return;file.text().then(text=>set({records:[...w.records,...parseImport(text,file.name)]}));e.target.value=''}
 function updateRecord(id,patch){set({records:w.records.map(x=>x.id===id?{...x,...patch}:x)})}
 function loadExample(){set({concepts:[{id:'p',label:'Population / Problem',terms:['hypertension','high blood pressure'],included:true},{id:'i',label:w.framework==='PICO'?'Intervention':'Exposure',terms:['telemonitoring','remote monitoring'],included:true},{id:'c',label:'Comparison',terms:['usual care'],included:false},{id:'o',label:'Outcome',terms:['blood pressure control'],included:false}]})}
 return <><PageHead eyebrow="Research Lab" title="Systematic Review Workspace" desc="Rancang strategi lintas basis data, dokumentasikan pencarian, dan telusuri setiap angka PRISMA ke record Anda."/><main className="wrap review-workspace">
  <nav className="review-tabs" aria-label="Tahap systematic review">{[['strategy','1. Strategi'],['searches','2. Log pencarian'],['screening','3. Screening'],['extraction','4. Ekstraksi'],['prisma','5. PRISMA']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {tab==='strategy'&&<div className="strategy-grid"><Card className="workspace-card"><div className="split-head"><div><Badge>PERTANYAAN</Badge><h2>PICO / PECO builder</h2></div><select value={w.framework} onChange={e=>framework(e.target.value)}><option>PICO</option><option>PECO</option></select></div><p className="muted">Satu kotak per sinonim. Sinonim digabung dengan <b>OR</b>; konsep berbeda dengan <b>AND</b>.</p><div className="concept-list">{w.concepts.map(c=><section key={c.id}><div className="concept-head"><b>{c.id.toUpperCase()} · {c.label}</b>{['c','o'].includes(c.id)&&<label className="inline-check"><input type="checkbox" checked={c.included} onChange={e=>concept(c.id,{included:e.target.checked})}/> Sertakan dalam query</label>}</div>{c.terms.map((term,i)=><div className="term-row" key={i}><input aria-label={`${c.label} sinonim ${i+1}`} value={term} placeholder="Istilah bebas / sinonim" onChange={e=>concept(c.id,{terms:c.terms.map((x,j)=>j===i?e.target.value:x)})}/>{c.terms.length>1&&<button aria-label="Hapus sinonim" onClick={()=>concept(c.id,{terms:c.terms.filter((_,j)=>j!==i)})}><Trash2/></button>}</div>)}<button className="text-action" onClick={()=>addTerm(c.id)}><Plus/> Tambah sinonim</button></section>)}</div><div className="sensitivity-note"><b>Mengapa Comparison dan Outcome opsional?</b><p>Istilah comparison dan outcome sering tidak muncul di judul/abstrak atau belum konsisten diindeks. Mengeluarkannya menjaga sensitivitas (mengurangi risiko studi relevan terlewat), dengan konsekuensi lebih banyak record perlu disaring.</p></div><Button onClick={loadExample}>Isi contoh</Button></Card>
  <div><Card className="workspace-card"><Badge>GENERATOR</Badge><h2>Basis data & filter</h2><div className="field-grid"><label>Basis data<select value={w.database} onChange={e=>set({database:e.target.value,platform:DATABASES[e.target.value].platforms[0]})}>{Object.keys(DATABASES).map(x=><option key={x}>{x}</option>)}</select></label><label>Platform / antarmuka<select value={w.platform} onChange={e=>set({platform:e.target.value})}>{DATABASES[w.database].platforms.map(x=><option key={x}>{x}</option>)}</select></label><label>Tahun mulai<input type="number" value={w.yearFrom} onChange={e=>set({yearFrom:e.target.value})}/></label><label>Tahun akhir<input type="number" value={w.yearTo} onChange={e=>set({yearTo:e.target.value})}/></label><label>Jenis studi<select value={w.studyType} onChange={e=>set({studyType:e.target.value})}><option value="all">Semua jenis studi</option><option value="rct">Randomized trial</option><option value="review">Systematic review</option></select></label></div></Card><Card className="query-preview"><div className="split-head"><div><Badge>{w.database} · {w.platform}</Badge><h2>Query siap salin</h2></div><button onClick={()=>navigator.clipboard.writeText(output.query)}><Copy/> Salin</button></div><code>{output.query||'Isi minimal satu konsep untuk membuat query.'}</code>{output.notes.map(x=><p className="filter-note" key={x}>{x}</p>)}<p className="candidate-note"><b>Subject headings belum ditambahkan otomatis.</b> MeSH/Emtree dan subject heading lain harus diperlakukan sebagai <b>kandidat</b> sampai diverifikasi di thesaurus resmi platform.</p><Button onClick={logSearch} disabled={!output.query}>Catat strategi ini</Button></Card></div></div>}
  {tab==='searches'&&<Card className="workspace-card"><div className="split-head"><div><Badge>AUDIT TRAIL</Badge><h2>Log pencarian manual</h2></div><Button onClick={logSearch} disabled={!output.query}>Tambah query aktif</Button></div><p className="muted">Aplikasi tidak mengakses basis data dan tidak mengarang jumlah hasil. Jalankan query secara manual, lalu isi jumlah dan nama file ekspor.</p>{w.searches.length?<div className="table-scroll"><table><thead><tr><th>Basis data / platform</th><th>Tanggal</th><th>Query lengkap</th><th>Jumlah hasil</th><th>File ekspor</th></tr></thead><tbody>{w.searches.map(s=><tr key={s.id}><td><b>{s.database}</b><small>{s.platform}</small></td><td><input type="date" value={s.date} onChange={e=>updateSearch(s.id,{date:e.target.value})}/></td><td><textarea value={s.query} onChange={e=>updateSearch(s.id,{query:e.target.value})}/></td><td><input type="number" min="0" value={s.count} placeholder="Isi manual" onChange={e=>updateSearch(s.id,{count:e.target.value})}/></td><td><input value={s.file} placeholder="contoh: pubmed.ris" onChange={e=>updateSearch(s.id,{file:e.target.value})}/></td></tr>)}</tbody></table></div>:<p className="empty-inline">Belum ada pencarian tercatat.</p>}</Card>}
  {tab==='screening'&&<Card className="workspace-card"><div className="split-head"><div><Badge>RECORDS & REPORTS</Badge><h2>Screening aktual</h2></div><div className="button-row compact"><label className="btn"><FileUp/> Impor RIS/CSV<input hidden type="file" accept=".ris,.csv,text/csv" onChange={importRecords}/></label><Button variant="outline" onClick={()=>set({records:deduplicate(w.records)})}>Deduplikasi</Button></div></div><p className="muted">Deduplikasi memakai DOI yang dinormalisasi, lalu judul ternormalisasi bila DOI kosong. Periksa hasil sebelum melanjutkan.</p>{w.records.length?<div className="record-list">{w.records.map(r=><article key={r.id}><div><b>{r.title}</b><small>{[r.year,r.source,r.doi].filter(Boolean).join(' · ')||'Metadata terbatas'}</small><p>{r.abstract||'Abstrak tidak tersedia.'}</p></div><label>Judul–abstrak<select value={r.status} onChange={e=>updateRecord(r.id,{status:e.target.value})}><option value="pending">Belum dinilai</option><option value="included">Lanjut full text</option><option value="excluded">Eksklusi</option></select></label>{r.status==='included'&&<><label>Full text<select value={r.fullText} onChange={e=>updateRecord(r.id,{fullText:e.target.value})}><option value="pending">Belum dinilai</option><option value="included">Inklusi</option><option value="excluded">Eksklusi</option></select></label><label>ID study<input value={r.studyId} placeholder="Kelompokkan multiple reports" onChange={e=>updateRecord(r.id,{studyId:e.target.value})}/></label></>}{(r.status==='excluded'||r.fullText==='excluded')&&<label>Alasan eksklusi<input required value={r.reason} placeholder="Wajib diisi" onChange={e=>updateRecord(r.id,{reason:e.target.value})}/></label>}</article>)}</div>:<p className="empty-inline">Impor file RIS atau CSV untuk mulai screening.</p>}</Card>}
  {tab==='extraction'&&<Card className="workspace-card"><div className="split-head"><div><Badge>STUDIES</Badge><h2>Tabel ekstraksi</h2></div><Button onClick={()=>saveFile('ekstraksi.csv',['Study ID,Report,Desain,Populasi,Intervensi,Comparison,Outcome,Catatan',...w.records.filter(r=>r.fullText==='included').map(r=>`${r.studyId||r.id},"${r.title.replaceAll('"','""')}",,,,,,`)].join('\n'),'text/csv')}><Download/> Ekspor CSV</Button></div><div className="table-scroll"><table><thead><tr><th>Study ID</th><th>Report</th><th>Desain</th><th>Populasi</th><th>Intervensi / exposure</th><th>Comparison</th><th>Outcome</th><th>Catatan</th></tr></thead><tbody>{w.records.filter(r=>r.fullText==='included').map(r=><tr key={r.id}><td>{r.studyId||r.id}</td><td>{r.title}</td>{['design','population','intervention','comparison','outcome','notes'].map(f=><td key={f}><textarea value={r[f]||''} onChange={e=>updateRecord(r.id,{[f]:e.target.value})}/></td>)}</tr>)}</tbody></table></div>{!w.records.some(r=>r.fullText==='included')&&<p className="empty-inline">Study muncul setelah report lolos penilaian full text.</p>}</Card>}
  {tab==='prisma'&&<><Card className="workspace-card prisma-card"><Badge>PRISMA 2020</Badge><h2>Alur dari record yang dikelola</h2><p className="muted">Semua angka dihitung langsung dari status record—bukan estimasi. “Reports” adalah dokumen; beberapa report dapat memakai satu Study ID.</p><div className="prisma-flow"><div><small>RECORDS</small><b>{flow.records}</b><span>Diimpor</span></div><i>↓</i><div><small>RECORDS</small><b>{flow.screened}</b><span>Disaring judul–abstrak</span></div><aside><b>{flow.taExcluded}</b><span>Records dieksklusi</span></aside><i>↓</i><div><small>REPORTS</small><b>{flow.reportsSought}</b><span>Full text dicari</span></div><i>↓</i><div><small>REPORTS</small><b>{flow.fullAssessed}</b><span>Dinilai kelayakan</span></div><aside><b>{flow.fullExcluded}</b><span>Reports dieksklusi full text</span></aside><i>↓</i><div className="included-box"><small>STUDIES / REPORTS</small><b>{flow.studies} / {flow.reportsIncluded}</b><span>Studies included / reports included</span></div></div></Card><div className="button-row"><Button onClick={()=>saveFile('workspace-systematic-review.json',JSON.stringify(w,null,2))}><Download/> Ekspor workspace JSON</Button></div></>}
 </main></>
}
