import React,{useEffect,useRef} from 'react';import {Link} from 'react-router-dom';import * as Icons from 'lucide-react';
export function Icon({name='Activity',size=20}){let C=Icons[name]||Icons.Activity;return <C size={size}/>}
export function Button({children,to,variant='primary',...p}){let cls=`btn ${variant}`;return to?<Link className={cls} to={to} {...p}>{children}</Link>:<button className={cls} {...p}>{children}</button>}
export function Card({children,className=''}){return <div className={`card ${className}`}>{children}</div>}
export function Badge({children,tone=''}){return <span className={`badge ${tone}`}>{children}</span>}
export function PageHead({eyebrow,title,desc,crumb}){return <><div className="wrap page-crumb"><Breadcrumb current={crumb||title}/></div><header className="page-head wrap"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></header></>}
export function Empty({text='Belum ada data yang sesuai.'}){return <div className="empty"><Icons.Inbox/><b>{text}</b><span>Coba ubah pencarian atau filter Anda.</span></div>}
export function Progress({value,label='Progres'}){return <div className="progress" role="progressbar" aria-label={label} aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round(value)}><i style={{width:`${value}%`}}/></div>}
export function Breadcrumb({current}){return <nav className="crumb" aria-label="Breadcrumb"><Link to="/">Beranda</Link><Icons.ChevronRight size={14}/><span aria-current="page">{current}</span></nav>}
export function Modal({open,onClose,children,label='Dialog'}){const box=useRef(null),previous=useRef(null);useEffect(()=>{if(!open)return;previous.current=document.activeElement;const node=box.current;node?.querySelector('button,input,a,select,textarea,[tabindex]:not([tabindex="-1"])')?.focus();function keys(e){if(e.key==='Escape')onClose();if(e.key==='Tab'&&node){const focusable=[...node.querySelectorAll('button,input,a,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',keys);document.body.classList.add('no-scroll');return()=>{document.removeEventListener('keydown',keys);document.body.classList.remove('no-scroll');previous.current?.focus()}},[open,onClose]);if(!open)return null;return <div className="modal-bg" onMouseDown={onClose}><div ref={box} className="modal" role="dialog" aria-modal="true" aria-label={label} onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={onClose} aria-label="Tutup dialog"><Icons.X/></button>{children}</div></div>}
